### ISSUE TITLE
cloud-init settings application

### ISSUE THREAD

**Issue by imikushin** [rancherio/os#102]
What does RancherOS' cloud-init implementation do exactly? Does it scan the cloud-config / user-data settings on every boot and applies them idempotently (that's my impression, but I might be wrong)? 

Documentation on the topic is scattered and unclear: 

- from original cloudinit docs I get the impression it runs only on first boot, 
- from CoreOS cloudinit-cloud-config doc I see it runs on every boot.

RancherOS docs list the settings (and I guess the list is not complete), but don't specify at what moment they are applied. 

BTW, is it possible that settings be applied immediately, e.g. on `rancherctl config set`, without reboot?

**Comment by ibuildthecloud** [comment]
We are still working on having all the setting in rancherctl be dynamic and not require reboot, but for now a reboot is required (really bugs me too).

cloud-init is ran on every boot and will look at the data sources configured from cloud_init.datasources.
