### ISSUE TITLE
HVM support

### ISSUE THREAD

**Issue by jacobwgillespie** [rancherio/os#111]
It would be awesome if there were HMV AMIs - I'd love to put RancherOS on a r3-class instance.

**Comment by ibuildthecloud** [comment]
@cloudnautique Is there anything that is preventing us from creating HVM images too?

**Comment by cloudnautique** [comment]
Not sure, Havent had time to try it. I can take a look in the next release cycle.

**Comment by cloudnautique** [comment]
HVM AMIs have been added for v0.3.0. Also, the installer can now handle it.
