### ISSUE TITLE
how to connect RancherOS host to docker-machine

### ISSUE THREAD

**Issue by cglewis** [rancherio/os#118]
Is it running with TLS so `tcp://<host_ip>:2376` or something else?  If it's TLS, where are the certs stored?  For example, `boot2docker` stores them in `~/.boot2docker`.   Also is there a plan to add a driver to `docker-machine` for this natively to start a new RancherOS host?

**Comment by wlan0** [comment]
@cglewis - TLS is configurable in rancherOS. It can be set with `userdocker.tls` config parameter in rancherctl. i.e. `rancherctl config set userdocker.tls true`

If tls is set, then the certs are stored in /etc/docker/tls in the userdocker contianers. You can access it by

`docker run -it -v /etc/:/etc ubuntu` and the `cd` into `/etc/docker/tls/`

Yes, we are currently working on adding support for RancherOS for docker-machine

**Comment by cglewis** [comment]
@wlan0 setting to `true` there was no directory `tls` after doing that, just a `key.json` file in `/etc/docker`

I tried putting the following in `/var/lib/rancher/conf/user_config.yml`:

```
user_docker:
  tls_args: [--tlsverify, --tlscacert=ca.pem, --tlscert=server-cert.pem, --tlskey=server-key.pem, '-H=0.0.0.0:2376']
  args: [docker, -d, -s, overlay, -G, docker, -H, 'unix:///var/run/docker.sock']
```

but that didn't seem to do anything either.  Nothing is listening on `tcp/2376` as far as I can find.  I know the `user_config.yml` is at least partially working, since it's taking my ssh key.  Is there some other step I'm missing?

**Comment by wlan0** [comment]
@cglewis You need to reboot after setting the config.

i.e. 

- `sudo rancherctl config set user_docker.tls true`
- `sudo reboot`

then bind mount /etc into a ubuntu container and then check `/etc/docker/tls`

**Comment by cglewis** [comment]
@wlan0 yup, did that, but no difference.  I'll try starting again from scratch later this week in case I screwed something up.

**Comment by ibuildthecloud** [comment]
@cglewis  Sorry for not responding more quickly to this.  We do have good TLS support but it was undocumented.  I just added documentation right now at https://github.com/rancherio/os/blob/master/docs/rancherctl-tls.md.  Please let me know if those instructions don't work.

Docker machine support is very important to us.  We are working to make RancherOS work perfectly with Machine and be available in all the drivers.  You can see Evan has branch that has RancherOS working with the Machine VirtualBox driver https://github.com/ehazlett/machine/tree/rancher-os

**Comment by cglewis** [comment]
@ibuildthecloud thanks, those docs were super helpful.  Looks good!
