### ISSUE TITLE
To run Weave in system-docker, there needs to be networking

### ISSUE THREAD

**Issue by errordeveloper** [rancherio/os#123]
Weave router normally runs in a network namespace, it's currently not possible to run it on RacherOS' system-docker out-of-the box.

**Comment by imikushin** [comment]
I'm not sure what you're trying to do, but maybe `--net=host` would help?

**Comment by errordeveloper** [comment]
@imikushin yes, that's a work-around for the time being. I have discussed this with @ibuildthecloud, and the origibal issue for running systemd Docker with `-b=none` was due to the dependency on `iptables`  command. I just logged it here so it doesn't get forgotten.

**Comment by ibuildthecloud** [comment]
Flocker also needs networks so it seems we will be setting up a bridge for system-docker

**Comment by deniseschannon** [comment]
This should be fixed in v0.3.0. Please re-open if you have any issues.
