### ISSUE TITLE
setting up ssh and obtaining the keys

### ISSUE THREAD

**Issue by squillace** [rancherio/os#136]
Hi -- just starting out with this, but I've read the docs I could find and I understand that I'm supposed to:

1. sudo rancherctl config set user_docker.tls true
2. sudo system-docker restart userdocker
3. sudo rancherctl tls generate -s --hostname localhost --hostname something.example.com
4. sudo system-docker restart userdocker
5. sudo rancherctl tls generate
6. sudo chown -R rancher ${HOME}/.docker

Given that I'm prepping a very simple image to try in one of the currently-unsupported clouds, how is it that it would be best to prep this image with a key/pair that you'd like to use? Or, more to the point, how is it that you should configure the image such that you can create a vm from it and immediately access it from ssh in order to configure the keys for remote docker usage? is there a way to use rancherctl remotely, or is that the point of rancher itself?

What's the best practice here?

Thanks in advance,  Ralph

**Comment by ibuildthecloud** [comment]
Those steps are for generating TLS keys for remote access for Docker.  If you want to setup SSH keys that is a bit different.  If you want to create an image that has an SSH key prepopulated I would probably follow the instructions to install to disk.  https://github.com/rancherio/os#installing-to-disk

If you used that approach you can create a cloud-config that has an SSH key in it and the installation script will prepopulate the disk with that cloud-config.

**Comment by squillace** [comment]
Great, thanks. I'll try that today. To confirm for the newbiediot here, if you wanted to create a vm image to use with any particular host *and* retain control over the VM once deployed, you'd create an image with the cloud-config file opening up SSH and adding the keys required. Correct?

And once deployed -- help orient me here -- when I ssh'd in, I'd be.... where? in user rancher, assuming I'd `ssh rancher@ranchervm.cloud.com -p 22`? From there I could connect to any of the command or user containers like normal?

Thanks for the help; I'm really looking forward to trying it all out.

**Comment by deniseschannon** [comment]
@squillace Please let me know if you were able to get this to work. And to answer your question, yes, you should be able to add the SSH keys into the cloud config file and create the image with them. 

You would ssh with `ssh rancher@ip_address` and would have access like normal.

**Comment by deniseschannon** [comment]
@squillace I'm going to close this issue and assume you've figured it out. If you are still having issues, please feel free to re-open.
