### ISSUE TITLE
Problem creating ISO Templating on CloudStack

### ISSUE THREAD

**Issue by ungarida** [rancherio/os#138]
Hi everybody,
I'm getting this error during ISO template creation on CloudStack:

```
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

My IaaS provider has CloudStack 4.4.0-SNAPSHOT and I used other times without problems the functionality of create ISO.

I used the linked provided by your documentation https://github.com/rancherio/os/releases/download/v0.2.1/rancheros.iso

**Comment by ibuildthecloud** [comment]
That error typically means that CloudStack can not validate the SSL certificate of the download URL.  It could be that the CloudStack installation is using outdated CA roots.

Can you try putting the ISO on a http URL, not HTTPS?

**Comment by ungarida** [comment]
I had topublish the iso on http, now it works.
thanks, now I can do some experiments and have fun!
