### ISSUE TITLE
NIC selection during install

### ISSUE THREAD

**Issue by sheng-liang** [rancherio/os#141]
On a server with multiple NICs, there needs to be a way to select and pin a NIC for RancherOS install. Ideally the system should behave as follows:

1. There should be a rancheros-install option to specify the MAC address of the NIC to use. Or put the NIC selection in user_config.yml file?

2. If the NIC selection is not there, rancheros-install can perhaps list all the NICs and prompt the user to select one?

Sheng

**Comment by ibuildthecloud** [comment]
We have support for selecting a NIC based on a Mac address.  It is possible that PR is not merged.  I'll look into that.

**Comment by sheng-liang** [comment]
It's also possible I just don't know about this feature. Is it documented anywhere?

**Comment by ibuildthecloud** [comment]
No, it's not documented.  We are refactoring docs right now so I don't want to make any changes.  Let's leave this issue open until it is documented.  In the meantime try the following in your cloud-config.yml

```yaml
#cloud-config
rancher:
  network:
    interfaces:
      "mac=00:00:00:00:00:00":
        dhcp: true
```

**Comment by deniseschannon** [comment]
Need to add to docs

**Comment by deniseschannon** [comment]
Added to docs within configuration/networking
