### ISSUE TITLE
No keyboard control on physical machine

### ISSUE THREAD

**Issue by JemiloII** [rancherio/os#159]
I own a system with 64GB of 1600Mhz ram, two 16core AMD opteron 6272, and 12tb of hdd. When I attempt to boot from a usb, it'll load the os and when when it comes to the login, my keyboard, which works just fine in that systems bios and other systems, doesn't work. Its as if the os has no clue what to do.

**Comment by ibuildthecloud** [comment]
Please try 0.3.0-rc2.  0.2.1 has very poor support for bare metal.  In the upcoming 0.3.0 release we have focused a lot on getting better bare metal support.

**Comment by charliedrage** [comment]
@JemiloII 
Are you trying to install this to bare-metal? If so, as far as I know, bare-metal isn't supported yet until the next version of rancher.

@ibuildthecloud can correct me if im wrong.

**Comment by JemiloII** [comment]
i'll try 0.3, thanks :)

**Comment by JemiloII** [comment]
alright, so 0.3.0-rc2 you can use a keyboard that's not bluetooth based. The 0.2.1 was no dice on either keyboard type. Gunna mark it has closed/solved thanks guys :)

**Comment by ibuildthecloud** [comment]
I imagine Bluetooth needs some user space component we don't have.

**Comment by vincent99** [comment]
Yes.. http://www.bluez.org/
