### ISSUE TITLE
Network unreachable when booting from iso (v0.3.0-rc2)

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/os#161]
Version: v0.3.0-rc2

Booted from iso using virtualbox, but can't reach network.

```bash
$ docker pull rancher/server:latest
Pulling repository rancher/server
FATA[0000] Get https://index.docker.io/v1/repositories/rancher/server/images: dial 
tcp: lookup index.docker.io on 8.8.4.4:53: dial udp 8.8.4.4:53: network is unreachable
```

**Comment by deniseschannon** [comment]
For v0.3.0-rc2:

The network adapter is getting renamed to `en2ps*`, which is why it doesn't get an IP through DHCP. 

For a temporary fix:

In the VM in VirtualBox, go to  Network Settings -> Advanced Settings.

Change "Adapter Type" to  "Paravirtualized Network (virtio-net)".

**Comment by deniseschannon** [comment]
Fixed in v0.3.0-rc3.

**Comment by maslick** [comment]
Same thing using Xen farm.
rancheros.iso: v0.3.0 (latest)

Had to edit /etc/resolv.conf manually, restarted the network. Now can reach network, but pulling any docker image results in: 
```
Pulling repository rancher/agent
FATA[0025] Get https://index.docker.io/v1/repositories/rancher/os/images: dial tcp: lookup index.docker.io on 8.8.4.4:53: read udp 8.8.4.4:53: i/o timeout ```

**Comment by deniseschannon** [comment]
@maslick Is the network adapter getting renamed in your setup? The originally filed bug was due to a change that renamed network adapters, but in v0.3.0, that should have been fixed.

**Comment by maslick** [comment]
@deniseschannon yeah, it's eth0

**Comment by deniseschannon** [comment]
If it's eth0, then the network adapater renaming isn't the issue. Since this bug is closed, could you start a new bug with some more details on how you edited the file to get it to work? Thanks!
