### ISSUE TITLE
Rolling back from v0.3.0-rc2 throws error

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/os#164]
v0.3.0-rc2

Trying to roll back from v0.3.0-rc2 and it throws an error. This is when trying to go to v0.3.0-rc1 or v0.2.1

```bash
[rancher@rancher ~]$ sudo rancherctl -v
rancherctl version v0.3.0-rc2
[rancher@rancher ~]$ sudo rancherctl os upgrade -i rancher/os:v0.2.1
Upgrading to rancher/os:v0.2.1
Continue [y/N]: y
"logs" endpoint is supported only for "json-file" logging driver
Error running logs job: "logs" endpoint is supported only for "json-file" logging driver
```

**Comment by deniseschannon** [comment]
Also, if I actually reboot the system, the upgrade appears to be successful.

**Comment by ibuildthecloud** [comment]
This is an error in the logging.  We switched to syslog by default and the os-installer seems incompatible with this

**Comment by ibuildthecloud** [comment]
Oh wait... This is a bug in os, not os-installer.  I'll fix this
