### ISSUE TITLE
Docker 1.5+ required for building ISO

### ISSUE THREAD

**Issue by schugh01** [rancherio/os#172]
Docker 1.5+ required for building ISO. This is an issue because we want to edit your iso without installing docker. You have solution for this issue?

**Comment by ibuildthecloud** [comment]
It's pretty difficult to remove the need for docker in the build.  Can you elaborate on why you can't or don't want to install Docker?  You're always free to modify the ISO using tools like genisoimage, but I'm not sure what you would be adding to the ISO.

**Comment by deniseschannon** [comment]
@schugh01 I'm going to close this issue, but if you have further feedback, please feel free to reopen.
