### ISSUE TITLE
rancherctl service enable: when using a custom service, it's annoying that the file must be placed in a specific folder location

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/os#209]
It's annoying that I have to save a folder in a specific folder location (`/var/lib/rancher/conf/`) AND I have to name the the service `/var/lib/rancher/conf/example.yml` in order for my service to work.

**Comment by deniseschannon** [comment]
enforce needing the location of a service enabled to either `/var/lib/rancher/conf` or `/home` or `/opt`

**Comment by wlan0** [comment]
@deniseschannon What is needed here?

**Comment by deniseschannon** [comment]
yes, basically an error message indicating that the yaml file needs to be in `/var/lib/rancher/conf/` if it can't be found.

right now, we add in the name of the service into the rancher.yml even if the file isn't located in that directory  like i did `rancherctl service enable test.yml` which obviously wouldn't work.

**Comment by ibuildthecloud** [comment]
I think enable should validate that the service is

1) A name that contains no `/`
2) A file that exists and starts with `/var/lib/rancher/conf`
3) A url that starts with http:// or https://

**Comment by wlan0** [comment]
@ibuildthecloud If you look at the code change I made, the above three cases are taken care of. 

https://github.com/rancherio/os/pull/273

**Comment by ibuildthecloud** [comment]
I didn't realize #1, #2 was taken care of.  I'll try to run the code.

**Comment by wlan0** [comment]
@ibuildthecloud  -- If #1 is not met, then it throws an error
It doesn't enforce #2, but we have been following the convention of putting these files in `/var/lib/rancher/conf`. I should enforce it. I will make that change now

**Comment by wlan0** [comment]
@ibuildthecloud I've pushed the changes to enforce #2.

**Comment by wlan0** [comment]
Also, Im guessing #1 means no trailing `/` right?

**Comment by deniseschannon** [comment]
Just tested this out with `rancherctl service enable test.yml`. The error message was "could not load service". Would it be okay if we made the change so that if the service ended in `.yml`, it shows the message that the file needs to be in `/var/lib/rancher/conf`?

**Comment by ibuildthecloud** [comment]
We can check if it doesn't start with http then print that message.

**Comment by deniseschannon** [comment]
@ibuildthecloud just made the PR.
