### ISSUE TITLE
expose: in service, this setting does not set any exposed ports

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/os#216]
v0.3.0

Enabling a service with this yaml code doesn't work:

```yaml
expose: 
- "3000"
```

When I do a docker inspect on the container created with the yaml file, the container doesn't have the port exposed:

```
"ExposedPorts": {
            "443/tcp": {},
            "80/tcp": {}
        },
```

**Comment by deniseschannon** [comment]
@ibuildthecloud the commit with the port bindings and exposed port setting did not fix the `expose` ports. 

https://github.com/rancherio/os/commit/b2ece712376e72069f15d85fe8bf413922b6bd32

**Comment by ibuildthecloud** [comment]
That commit should have fixed "ports" but not expose.  Need more code for expose.
