### ISSUE TITLE
hostname: in service, this setting is not being set

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/os#217]
v0.3.0

Enabling a service with this yaml code doesn't work:

```yaml
hostname: test
```

When I do a docker inspect on the container created with the yaml file, the hostname is not updated to "test", it's still at "rancher".

```
"Config": {
            "Hostname": "rancher",
        },
```

**Comment by deniseschannon** [comment]
if net: host, then hostname will not work. i've added to the document about hostname.

**Comment by SatWiz** [comment]
can you explain why hostname can not set if net: host? How do I distinct my hosts if all host are named rancher? I would like to change hostname afterwards when boot from iso.

**Comment by deniseschannon** [comment]
@imikushin do you know why the hostname is being overridden when net:host?

As for changing hostname after booting from iso. here's some documentation i found on the docker site. The only downside is that anytime you reboot and containers are restarted, you will need to reset the hostname.

https://docs.docker.com/articles/networking/

At the bottom of the page, it says this: 
Editing networking config files
Starting with Docker v.1.2.0, you can now edit /etc/hosts, /etc/hostname and /etc/resolve.conf in a running container. This is useful if you need to install bind or other services that might override one of those files.

Note, however, that changes to these files will not be saved by docker commit, nor will they be saved during docker run. That means they won't be saved in the image, nor will they persist when a container is restarted; they will only "stick" in a running container.

**Comment by imikushin** [comment]
I've read about it in docker issues. This is dark matter. 

There'll be a new flag in docker 1.7, `--uts=host`, for using host's hostname. Now, only in RancherOS (because of a patch we're applying for our version of Docker) --net=host overrides container's hostname with host's.

**Comment by SatWiz** [comment]
I am quite new about rangeros and compares it a little bit with coreos. With coreos, hostname can be set (in cloud-init). I don't see why it should be fixed in rangeros.
