### ISSUE TITLE
`restart: always` not applied to services in compose format

### ISSUE THREAD

**Issue by imikushin** [rancherio/os#230]
Repro:
  1. `rancherctl s enable https://gist.githubusercontent.com/imikushin/fec33701294b77641022/raw/d6c488f0fb1cb21d60e9d8b64c5a1e4abff767fe/nginx.yml`
  2. Reboot.
  3. Wait until `nginx` container is started. `docker ps -a` shows the container is running.
  4. Simulate container main process failure:  
`ps -ef | grep 'nginx: master' | awk '{print $2}' | xargs -I{} kill {}`
  5. `docker ps -a` shows `nginx` container is NOT running.

If I just use docker CLI to run a container with `--restart=always` and kill its main process from outside, the container gets restarted as expected.

**Comment by ibuildthecloud** [comment]
The compose parser is quiet incomplete at the moment.  Will fix.  I honestly thought this one worked, but obviously not.

**Comment by imikushin** [comment]
I tried to fix this myself today, but got lost in config datastructures :)

**Comment by ibuildthecloud** [comment]
What!?  There's only four different data structures called all called config.  How could that be confusing :)

The code already has some cruft from the rapid iterations.  I can point you to what needs to been change in a bit.

Darren

**Comment by deniseschannon** [comment]
I didn't even see that this was enabled per #221. At least I didn't see it in the factory.go file. I'll close my issue in favor of this one.

**Comment by imikushin** [comment]
The same for core system services: adding `Restart: "always"` in their config code doesn't propagate to their containers' `HostConfig.RestartPolicy` property, so they don't get restarted.

**Comment by deniseschannon** [comment]
This looks fixed in v0.3.1-rc1, but @imikushin could you test this out for me? Just want a second tester.

**Comment by imikushin** [comment]
Confirm fixed.
