### ISSUE TITLE
Can't reach network from docker (8.8.4.4:53 issue)

### ISSUE THREAD

**Issue by maslick** [rancherio/os#240]
Similar to #161 , but internet seems to be working after a small fix in ```/etc/resolv.conf``` (add your dns server ip there: namespace xxx.yyy.zzz.nnn), but pulling any docker image results in:

```
Pulling repository rancher/agent
FATA[0025] Get https://index.docker.io/v1/repositories/rancher/os/images: dial tcp: lookup index.docker.io on 8.8.4.4:53: read udp 8.8.4.4:53: i/o timeout
```

resolv.conf:
```
#nameserver 8.8.8.8
#nameserver 8.8.4.4
domain xxxxx.com
search xxxxx.com
nameserver 10.5.0.x
```

P.S. after editing resolv.conf, restarted the network:
```
[rancher@rancher ~]$ sudo /etc/init.d/S40network restart        
Stopping network...ifdown: interface lo not configured
Starting network...
ip: RTNETLINK answers: File exists
```

```
[rancher@rancher ~]$ ifconfig 
docker-sys Link encap:Ethernet  HWaddr 62:ED:1C:92:E2:0C  
          inet addr:172.18.42.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::60ed:1cff:fe92:e20c/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:648 (648.0 B)

docker0   Link encap:Ethernet  HWaddr 56:84:7A:FE:97:99  
          inet addr:172.17.42.1  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

eth0      Link encap:Ethernet  HWaddr 8E:50:2E:35:AB:98  
          inet addr:10.5.2.106  Bcast:10.5.3.255  Mask:255.255.252.0
          inet6 addr: fe80::8c50:2eff:fe35:ab98/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:274863 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1638 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:18503215 (17.6 MiB)  TX bytes:314034 (306.6 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

**Comment by ibuildthecloud** [comment]
Please try configuring the DNS servers as described at http://rancherio.github.io/os/docs/configuring/

In sort run `rancherctl config set network.dns.nameservers '[10.5.0.x]'` and reboot.

**Comment by maslick** [comment]
Reboot restores all the settings back to the default.

**Comment by ibuildthecloud** [comment]
Are you running with a persistent disk?  After you run `rancherctl config set network.dns.nameservers '[10.5.0.x]'` can you look at /var/lib/rancher/conf/rancher.yml and see what is in there?

**Comment by maslick** [comment]
it's empty

**Comment by maslick** [comment]
I am running rancheros on a xen farm

**Comment by ibuildthecloud** [comment]
After running `sudo rancherctl config set network.dns.nameservers '[10.5.0.x]'` you should see in /var/lib/rancher/conf/rancher.yml (before reboot)

```yaml
network:
  dns:
    nameservers:
    - 10.5.0.x
```

If you don't have a persistent disk setup you are going to have to configure things either from a cloud-config (not sure how you'll do that in your environment) or from the kernel commandline.  If you can set the kernel command line you just need `rancher.network.dns.nameservers=[10.5.0.x]`  on the command line.

The easiest would be set setup a persistent disk.

**Comment by maslick** [comment]
Oh, sorry, had to use sudo to view the file. Yeah, I have this in rancher.yml:
```
network:
  dns:
    nameservers:
    - 10.5.0.x
```

**Comment by ibuildthecloud** [comment]
I'm assume you replaced 'x' with a real number.  You can do the same with search, so `rancherctl config set network.dns.search '[foo.com,bar.com]'`

When you reboot do you loose the configuration?

**Comment by maslick** [comment]
Yeah. I have a real number.And yes, everything is gone after reboot.

**Comment by ibuildthecloud** [comment]
So you haven't setup a disk to save state?  Can you do that.

    docker run --privileged -it debian mkfs.ext4 -L RANCHER_STATE /dev/xvda

Where /dev/xvda is the disk that will hold the state

**Comment by maslick** [comment]
```
[rancher@rancher ~]$ docker run --privileged -it debian mkfs.ext4 -L RANCHER_STATE /dev/xvda
Unable to find image 'debian:latest' locally
Pulling repository debian
FATA[0045] Get https://index.docker.io/v1/repositories/library/debian/images: dial tcp: lookup index.docker.io on 8.8.4.4:53: read udp 8.8.4.4:53: i/o timeout
```

**Comment by ibuildthecloud** [comment]
Right.... catch 22... hmmm...  We actually package mkfs.ext4 in the console so `mkfs.ext4 -L RANCHER_STATE /dev/xvda` should work

**Comment by maslick** [comment]
ok, that did work!

**Comment by ismail0352** [comment]
Hi 
I am facing exact same issue.
I tried all the steps  mentioned above , but still it didn't work for me.
Please, Can you help me to solve this issue?

**Comment by deniseschannon** [comment]
@ismail0352 what version of rancherOS are you running? and how did you get it launched?

Please try the steps in this order:
1. boot rancheros
2. `sudo mkfs.ext4 -L RANCHER_STATE /disk/name` this will allow a persisting state. 
3. `sudo reboot` if you do not reboot at this stage, any changes made will still not be saved.
4. after you reboot, `sudo rancherctl config set network.dns.nameservers '[10.5.0.x]'
5. check the `rancher.yml` file by running `sudo rancherctl config export`. it should show
```
network:
  dns:
    nameservers:
    - 10.5.0.x
```
6. `sudo reboot` so the changes will take effect

**Comment by ismail0352** [comment]
Sorry , It didn't work.
My steps and their output:
1) boot OS
2) sudo mkfs.ext4 -L RANCHER_STATE /dev/sda1
OutPut:
mke2fs 1.42.12 (29-Aug-2014)
/dev/sda1 contains a ext4 file system labelled 'RANCHER_STATE'
	last mounted on /var on Fri May 15 05:29:46 2015
Proceed anyway? (y,n) y
/dev/sda1 is mounted; will not make a filesystem here!

3) reboot
4) sudo rancherctl config set network.dns.nameservers '[10.5.0.15]'
5)sudo rancherctl config export

OutPut:
services_include:
  ubuntu-console: true
network:
  dns:
    nameservers: [10.5.0.15]
  interfaces:
    eth*: {}
    eth0:
      dhcp: true
    eth1:
      match: eth1
      address: 172.19.8.101/24
    lo:
      address: 127.0.0.1/8

6) reboot
7) sudo docker pull ubuntu

OutPut:
FATA[0025] Get https://index.docker.io/v1/repositories/library/ubuntu/images: dial tcp: lookup index.docker.io on 10.5.0.15:53: read udp 10.5.0.15:53: i/o timeout

**Comment by deniseschannon** [comment]
Can you tell me what version of RancherOS and how you are running it?

**Comment by ismail0352** [comment]
Version 0.3.0
Booting using Vagrant box: https://github.com/rancherio/os-vagrant

**Comment by imikushin** [comment]
@ismail0352 
10.5.0.15 is a private IPv4 address (in 10.0.0.0 - 10.255.255.255 range). 
Do you have a DNS server on 10.5.0.15 on your internal network? If not, it's not gonna work.

RancherOS uses Google's public 8.8.8.8 and 8.8.4.4 DNS servers by default. These are accessible almost everywhere (but can be blocked by some ISPs with ridiculous policies). There are also publicly available OpenDNS servers: 208.67.222.222, 208.67.220.220. 

Use one or more of those, e.g.:
```
sudo rancherctl config set network.dns.nameservers '[208.67.222.222, 208.67.220.220]'
reboot
```

If none of that works, ask your Internet provider about DNS server addresses that you can use.

**Comment by ismail0352** [comment]
Thanks,
My DNS server address are 172.27.172.12, 172.27.172.10
I tried this and it worked
1)sudo rancherctl config set network.dns.nameservers '[172.27.172.12, 172.27.172.10]'
2) reboot

**Comment by rahulmr** [comment]
Hi @ismail0352 , I am facing the same issue on vmware, could you please let me know how to find my DNS server addresses?

**Comment by ismail0352** [comment]
On windows - nslookup www.cybage.com    (www.cybage.com is your organization domain), this command will give you DNS address 

On Linux: check "nameserver" entry in /etc/resolve.conf , that will be your DNS address
