### ISSUE TITLE
RancherOS upgrade should check the current version to make sure it can be upgraded

### ISSUE THREAD

**Issue by sheng-liang** [rancherio/os#252]
The current doc says:

Let’s walk through upgrading! The rancherctl os upgrade command will automatically upgrade to the current release of RancherOS. The current release is designated as the most recent release of RancherOS. If you are a couple of versions behind, it’s recommended to upgrade to each subsequent versions as RancherOS doesn’t support going from v0.1.2 to v0.2.1 (skipping v0.2.0). 

So we should check the current version to make sure it can be upgraded and error out if it cannot.

**Comment by deniseschannon** [comment]
Need to update docs.

**Comment by deniseschannon** [comment]
Updated docs to remove requirements of upgrading to subsequent versions.
