### ISSUE TITLE
Should provide a warning when keys are in a service file don't exist or are not a valid key

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/os#291]
Currently, if you put an invalid key (due to a typo or lack of understanding of what's supported in rancher-compose), we should display a warning to the user so they know that the key wasn't used/read.

**Comment by wlan0** [comment]
Are you saying that if the syntax of rancher-compose file is wrong for a service, the user should be warned?

**Comment by deniseschannon** [comment]
Yes, this is what @ibuildthecloud had suggested when he used `export` instead of `expose` for a test case. Since `export` is not a valid key.

**Comment by deniseschannon** [comment]
Pre-duplicate of https://github.com/rancherio/rancher-compose/issues/32
