### ISSUE TITLE
ChangeLog / Release Notes

### ISSUE THREAD

**Issue by prologic** [rancherio/os#298]
Do we have any? Been a while since I looked at RahcerOS and I'd like to get more involved :)

**Comment by deniseschannon** [comment]
Currently, we have no change log or release notes. One way to see the changes is to view the difference between tags and you can see the commits that have been made in between release. It's not the easiest way to see the updates between releases, but it's the only way that I know of as now.

**Comment by prologic** [comment]
@deniseschannon Thanks :) It's better than nothing! I'll have a gander :)

**Comment by josegonzalez** [comment]
I'd like to have this re-opened. It's nice to at least see overarching changes between releases - what makes 0.4.0 different from 0.3.1 - and gives confidence to users of the platform.

**Comment by deniseschannon** [comment]
We are planning to add Release Notes for v0.4.0, so don't worry. :)

**Comment by josegonzalez** [comment]
<3

**Comment by janeczku** [comment]
+1 would appreciate to know whats new in v0.4.0

**Comment by deniseschannon** [comment]
Yes, we will be doing release notes and documentation and all the new stuff in v0.4.0. :)

**Comment by jfchevrette** [comment]
I was looking for a Changelog for 0.4.4 and found this issue. Is this still planned?

**Comment by deniseschannon** [comment]
You can look at the closed milestone of 4.4 to see what issues were fixed.
https://github.com/rancher/os/issues?q=is%3Aissue+milestone%3Av0.4.4+is%3Aclosed
