### ISSUE TITLE
Startup Errors: Boot order of containers is not correct

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/os#313]
After running `sudo mkfs.ext4 -L RANCHER_STATE /dev/sda`, I just continue to reboot.
 
If I continue to reboot over and over again (no changes to OS), you will eventually hit a startup error related to the start of containers.

The startup complains that `all-volumes` container is non-existent and doesn't start a series of other containers.

It also complains that the name "cloud-init-pre-982340825bc9823492349823" is already in use by another container and it needs to be deleted/renamed to be able to resue the container.

Once I get this error, my containers and names are all out of sync and it keeps complaining and will not start all of the system containers.

**Comment by imikushin** [comment]
Confirm reproduced.

**Comment by deniseschannon** [comment]
@imikushin Is this fixed with the container hashing?

**Comment by imikushin** [comment]
Yes
