### ISSUE TITLE
Make stable releases available under an IPXE compatible URL

### ISSUE THREAD

**Issue by janeczku** [rancherio/os#321]
RancherOS is the perfect candidate for deployment via IPXE.
But since IPXE doesn't work with Github hosted files (in fact it neither supports HTTPS nor 301 redirects), it would be nice if the stable release files were to be made available under a static HTTP URL (like is the case for CoreOS).

Here is my (perfectly working) RancherOS IPXE boot script:
```bash
#!ipxe
# Boot a persistent RangerOS to RAM

# Location of Kernel/Initrd images
set base-url http://privateserver

kernel ${base-url}/vmlinuz rancher.state.autoformat=[/dev/vda] rancher.cloud_init.datasources=[ec2]
initrd ${base-url}/initrd
boot
```

**Comment by ibuildthecloud** [comment]
For sure!   I didn't realize iPXE couldn't pull from HTTPS or redirects.  We are just about to release v0.3.1.  We will do this then.

**Comment by ibuildthecloud** [comment]
FYI @imikushin @cloudnautique

**Comment by janeczku** [comment]
@ibuildthecloud :100: awesome

**Comment by janeczku** [comment]
@ibuildthecloud any progress on this? I would like to make RancherOS the default OS in `docker machine`'s `Vultr` driver before the initial patch gets merged. https://github.com/docker/machine/pull/958

**Comment by imikushin** [comment]
@janeczku can you test these URLs:
```
http://storage.googleapis.com/ros-images/v0.3.1/vmlinuz
http://storage.googleapis.com/ros-images/v0.3.1/initrd
```

**Comment by janeczku** [comment]
Thanks @imikushin. These URLs are working of course. For iPXE deployment in general (and even more so for hard-coding the URL in docker-machine) we would want a static, non-versioned URL that points to the latest stable release.
Something like so: `http://storage.googleapis.com/ros-images/stable-releases/current/initrd`

**Comment by imikushin** [comment]
Hey @janeczku, check these out: 
```
http://releases.rancher.com/os/latest/vmlinuz
http://releases.rancher.com/os/latest/initrd
```

**Comment by janeczku** [comment]
@imikushin those look great! :)

**Comment by imikushin** [comment]
I updated the readme: #354

**Comment by deniseschannon** [comment]
@janeczku Looks like we have the URL working.

**Comment by matti** [comment]
ipxe can pull from https, if https support is enabled - just tried to boot rancher os with ipxe and https and it worked, except I got a kernel panic (hello from 2020)
