### ISSUE TITLE
Version Control - Should we remove the RC of versions that have officially released?

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/os#325]
After a version is released, should we remove the rc's of that release? For example, v0.2.0-rc1-3 and v0.3.0-rc1-4 is still available to download and still showing up when we run `sudo ros os list`.

**Comment by deniseschannon** [comment]
@imikushin Any opinion on this?

**Comment by imikushin** [comment]
If they are still available for download somewhere (on GitHub you can mark a version as pre-release), then it's probably a good idea.

I'm fine with keeping pre-release versions in `ros os list` only for upcoming releases.

**Comment by deniseschannon** [comment]
We'll only keep pre-release versions for upcoming releases. They will be removed once the release is out.
