### ISSUE TITLE
No /dev/kvm in RancherOS 0.3.1

### ISSUE THREAD

**Issue by pwFoo** [rancherio/os#397]
RancherOS should have kvm support as written in RancherVM readme file.
> You can run RancherVM on RancherOS. If you are running RancherOS 0.3.1 or later, KVM is already enabled in the kernel.

But /dev/kvm is missing?

**Comment by Xe** [comment]
```console
$ sudo modload kvm
```

Try that?

**Comment by pwFoo** [comment]
I think you mean modprobe? There is no command modload.

With **sudo modprobe kvm** the module is loaded sucessfully, but there is no /dev/kvm. How to create the device and tools like kvm / qemu-kvm are needed? Not found in RancherOS 0.3.1.

**Comment by ibuildthecloud** [comment]
This is quite odd, you shouldn't need to create it.  Let me test this and see if it's a regression because this has always worked. mknod is the command you need to create the device but I don't know the character numbers off the top of my head

**Comment by Xe** [comment]
@pwFoo Yeah, modprobe, that one

**Comment by sheng-liang** [comment]
Make sure your host has VT enabled. I have no problem seeing /dev/kvm and using KVM on 0.3.1. No need to modprobe.

**Comment by pwFoo** [comment]
You're right! Sorry for that! It was a host VT problem!!! Solved and works fine! Awesome feature!
