### ISSUE TITLE
Docs website is broken

### ISSUE THREAD

**Issue by far-blue** [rancherio/os#398]
All the urls for external resources (css, images, javascript) and all links on http://rancherio.github.io/os/ refer to the root url rather than the /os/ subfolder and so are broken.

**Comment by vincent99** [comment]
We changed to http://os.docs.rancher.com/ and updated the links on the home page.. Did you find an outdated URL somewhere or just have it bookmarked?

**Comment by far-blue** [comment]
Yeah, on the beta release blog article from 16th june :) Maybe you could do some sort of redirect to catch old references?

**Comment by vincent99** [comment]
Thanks, updated the blog post.  We can't do a real redirect since we don't control github.io but I could do something in JavaScript... They haven't existed for very long though so I think just fixing any links that are out there is good enough.

**Comment by far-blue** [comment]
Cool :) While you're at it, I also noticed that example cli command for creating a rancherOs VM via docker-machine is wrong. It is using the github url for the 0.3.1 tag rather than specifically the rancheros-machine.iso download. The command needs changing to use the url "https://github.com/rancherio/os/releases/download/v0.3.1/machine-rancheros.iso"

**Comment by deniseschannon** [comment]
@far-blue I updated the docs with the incorrect CLI.
