### ISSUE TITLE
Add AMI image in eu-central

### ISSUE THREAD

**Issue by ianbytchek** [rancherio/os#407]
Hi, I know there's #65 already mentioning this with a comment saying that eu-central will come shortly (nearly 5 months ago). Any chance this has progressed since then?

**Comment by ibuildthecloud** [comment]
Oh sorry, I think we just lost track of this issue.  @imikushin can we make sure we get this region added for 0.3.2?  There was some technical reason it wasn't supported before.  I think it was HVM only.

**Comment by moritzheiber** [comment]
Oh yes, please. I was about to actually start deploying RancherOS and the AMI for eu-central-1 is missing :/

**Comment by imikushin** [comment]
I'll look into it as soon as we've tagged v0.3.2 on GitHub. We do have HVM images in other regions, so it should probably work for eu-central-1 too.

**Comment by imikushin** [comment]
This is going to be addressed in v0.3.3. In fact, the images are ready now. So, for a sneak peek: 
https://gist.github.com/imikushin/65f7a8a8cf8ceb1b0297

**Comment by imikushin** [comment]
Sorry, wrong button

**Comment by imikushin** [comment]
The images are not public yet, but stay tuned.

**Comment by deniseschannon** [comment]
The release is publicly available. Please refer to our [README](https://github.com/rancherio/os/blob/master/README.md) for more details. The eu-central-1 is listed for both PV and HVM.
