### ISSUE TITLE
Upgrade from 0.3.1 to 0.3.2 not available

### ISSUE THREAD

**Issue by pwFoo** [rancherio/os#421]
The version 0.3.2 isn't listed (sudo ros os list), but released today. How long is the delay until it will be available?

**Comment by deniseschannon** [comment]
There is a small bug with the `machine-rancheros.iso`. We should have the official release by tomorrow. I'll definitely let you know when it's ready.

**Comment by imikushin** [comment]
RancherOS [v0.3.3](https://github.com/rancherio/os/releases/tag/v0.3.3) has been released. Please check it out. 

Feel free to reopen if there's any problem upgrading to v0.3.3.

**Comment by pwFoo** [comment]
Upgrade to 0.3.3 works eine.
