### ISSUE TITLE
EC2 compatible image in addition to AMI

### ISSUE THREAD

**Issue by gschukin** [rancherio/os#46]
Please publish EC2 compatible image in addtion to AMI.

**Comment by cloudnautique** [comment]
Just to clarify, do you mean just a raw disk image that you can lay down?

**Comment by gschukin** [comment]
Yes, we have our own private EC2 compatible cloud, that can understand qcow2 format.

**Comment by deniseschannon** [comment]
We'll do OpenStack issues. Please track using #261
