### ISSUE TITLE
What file system is used?

### ISSUE THREAD

**Issue by defunctzombie** [rancherio/os#49]
I can't seem to find details on what file system is being used by default. Apologies if I did not look hard enough.

**Comment by cloudnautique** [comment]
The AMIs and Vagrant box are all using ext4 for the state drive. If you boot from the ISO your running in memory. The docker storage driver is using OverlayFS.

**Comment by defunctzombie** [comment]
Thanks! Maybe this can find a place somewhere in the docs. For now it will be in issues incase anyone searches for it.
