### ISSUE TITLE
device out of space error when running iso on openstack/qemu

### ISSUE THREAD

**Issue by dudymas** [rancherio/os#61]
Given a virtual machine with the following stats:

  4 VCPUs
  8 GB RAM
  80 GB HDD

Running the latest rancheros.iso on qemu on openstack juno.

I expect that pulling two images, sameersbn/gitlab:7.8.1 and sameersbn/redis:latest , will succeed (assume the rancher-agent image already ran successfully).

Instead, the pull fails with 'no space remaining'. If I install docker on a trusty-taur vm of similar or smaller sizes, all steps above succeed with flying colors.

If you'd like more info, logs, etc... just ask. The machines are fairly beefeh:

![screen shot 2015-03-02 at 4 47 45 pm](https://cloud.githubusercontent.com/assets/928448/6451347/ea445790-c0fb-11e4-85bc-6481ebd29812.png)

**Comment by ibuildthecloud** [comment]
If you run from the ISO, RancherOS looks for a partition labels with RANCHER_STATE.  You can look at the readme for the exact command to create that.  If RancherOS can't find that filesystem it will just run out of memory.  I suspect you are running out of memory.

We have a to disk installer coming soon that would hopefully make it easier to run in Openstack.

@cloudnautique what's the easiest way at the moment to create a bootable disk?

**Comment by dudymas** [comment]
Awesome! Could I possibly fashion a metadata piece for this?

I'm sorta new to editing iso's, but I was looking at the scripts... I bet I could use the CoreOs libs for reading cloud-init's if you guys would allow it.

**Comment by ibuildthecloud** [comment]
@dudymas If you are running qemu w/ OpenStack I would assume that it is using virtio so the device would /dev/vda that you would want to format.

We only turn on 169.254.169.254 for the EC2 images, I believe if we turned it on for ISO then the boot maybe hang indefinitly waiting for 169.254.  We could make it a kernel command line option, but then that wouldn't be useful to OpenStack.

We want to have a proper OpenStack image and will be working on producing one.  If you can specify a volume with your VM there is a preformated qcow2 at https://github.com/rancherio/os/blob/master/assets/empty-hd.img.gz.  So boot from ISO and use that as your primary disk.

**Comment by dudymas** [comment]
Since this has a lot of good workarounds, AND there's going to be an installer, I'm considering this closed. Feel free to reopen if you'd rather use the issue to track the installer fellow.

Also, I'm going to be making a packer for rancher internally... but I'm pretty sure I could make it a PR if you guys like packer... thoughts?

**Comment by ibuildthecloud** [comment]
I believe packer is going to be our official approach to building images.  It's a WIP but you can see what @cloudnautique has been working on here https://github.com/cloudnautique/rancher-packer.  We'd love contributions.  I personally don't know much about Packer so I'm not sure what work needs to be done there.

**Comment by SatWiz** [comment]
Any progress creating a usable openstack qcow2 image? While boot from iso I don't have any usable block device to install to. I am using openstack nova and whould like to test rangeros :).

**Comment by dudymas** [comment]
I've been rolling my own qemu's from the isos, as we also deploy with openstack. packer might let you accomplish this. 

try nabbing packer from http://packer.io
then git clone https://github.com/cloudnautique/rancher-packer

cd to /vagrant

edit either json file to use fields in https://packer.io/docs/builders/qemu.html

I might have time to put something up on github for ya. just no promises on short notice.

**Comment by SatWiz** [comment]
Thanks for pointing to your solution. I will read the docs and will see to understand. But I just wonder if the wheel is already invented why there is no general openstack image with a variable user_data input made yet.
I have meanwhile played with rangeros on my own kvm server and must say it is way easier then coreos to manage. Great job!

**Comment by dudymas** [comment]
Well, we can certainly just make a PR to the packer scripts.

I agree we should add an image that takes user_data too. All you have to do is install cloudinit on the os via script... maybe I could just grab a build of https://github.com/coreos/coreos-cloudinit and have the rancher system docker run cloudinit in a rancher flavor (i.e. build it without the coreos flags).

put that on a phusion or alpine container, and it'd still be rather slim... could even tell it to clean up afterwards.

I'm going to rename this issue to be more specific and reopen to see what the rancher folks can say.
