### ISSUE TITLE
The vagrant feature “Synced folders” is not working on RancherOS… missed rsync?

### ISSUE THREAD

**Issue by ricardsonwilliams** [rancherio/os#63]

**Comment by ibuildthecloud** [comment]
Is that all that is needed?  Just SSH+rsync?   We don't have rsync today, but we could add it.

**Comment by ricardsonwilliams** [comment]
yes :) I think based the below error that only "rsync" should be add into rancherOS

==> default: Machine booted and ready!
"rsync" was not detected as installed in your guest machine. This
is required for rsync synced folders to work. In addition to this,
Vagrant doesn't know how to automatically install rsync for your
machine, so you must do this manually.

**Comment by ibuildthecloud** [comment]
No problem.  We should do a smaller release within the next release and we'll include rsync.

**Comment by ibuildthecloud** [comment]
@ricardsonwilliams v0.1.2 was just release and it now includes rsync.  Could you please try and see if the vagrant synced folders works now?

ping @cloudnautique

**Comment by ricardsonwilliams** [comment]
@ibuildthecloud did you update the Vagrant Box Image? ( http://cdn.rancher.io/vagrant/x86_64/prod/rancheros_virtualbox.box )

**Comment by cloudnautique** [comment]
We did update. Need to do the merge, but url is "http://cdn.rancher.io/vagrant/x86_64/prod/rancheros_v0.1.2_virtualbox.box"

**Comment by ricardsonwilliams** [comment]
Good! I update mine Vagrant's file but the rsync option still show a error:

Error message:

==> default: Rsyncing folder: /Users/ricardsonwilliams/GitHub/Vagrant2/rancherOS/ => /vagrant
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /Users/XXXX/GitHub/Vagrant2/rancherOS/
Guest path: /vagrant
Command: rsync --verbose --archive --delete -z --copy-links --no-owner --no-group --rsync-path sudo rsync -e ssh -p 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i '/Users/XXXXX/GitHub/Vagrant2/rancherOS/.vagrant/machines/default/virtualbox/private_key' --exclude .vagrant/ /Users/XXXXXX/GitHub/Vagrant2/rancherOS/ rancher@127.0.0.1:/vagrant
Error: Warning: Permanently added '[127.0.0.1]:2222' (RSA) to the list of known hosts.
rsync: This rsync lacks old-style --compress due to its external zlib.  Try -zz.
rsync error: syntax or usage error (code 1) at main.c(1554) [server=3.1.1]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /SourceCache/rsync/rsync-45/rsync/io.c(453) [sender=2.6.9]

**Comment by ricardsonwilliams** [comment]
I try to disable the option "vb.functional_vboxsf     = false"

==> default: Mounting shared folders...
    default: /vagrant => /Users/XXXXX/GitHub/Vagrant2/rancherOS
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t vboxsf -o uid=`id -u rancher`,gid=`getent group rancher | cut -d: -f3` vagrant /vagrant
mount -t vboxsf -o uid=`id -u rancher`,gid=`id -g rancher` vagrant /vagrant

The error output from the last command was:

mount: mounting vagrant on /vagrant failed: No such device

**Comment by ibuildthecloud** [comment]
We definitely don't have the guest additions yet.  We are working on that one.

**Comment by cloudnautique** [comment]
@ricardsonwilliams The latest os-vagrant/Vagrantfile has the vboxsf disabled. It ends up looking like

```
config.vm.provider "virtualbox" do |vb|
     vb.check_guest_additions = false
     vb.functional_vboxsf     = false
     vb.memory = "1024"
  end
```
 
We should have something up soon that will setup an rsync folder to /opt/rancher from the current directory.

**Comment by cloudnautique** [comment]
@ricardsonwilliams [rancherio/os-vagrant](https://github.com/rancherio/os-vagrant) Vagrantfile now has configuration to enable an rsync folder. It looks like the error we are seeing with the --compress flag, at least with OS X Yosemite, is that the version of rsync is really old (version 2.6.9). The RancherOS version is 3.1.1 which is the latest release.

**Comment by ricardsonwilliams** [comment]
@cloudnautique Thank you! Works pretty well. Nice you already update the os-vagrant readme file.

**Comment by DJviolin** [comment]
I've got the following error on Windows 7. I installed cwRsync free version. If I type in the command prompt: "rsync". I've got it run:

```Batchfile
$ rsync
rsync  version 3.1.1  protocol version 31
Copyright (C) 1996-2014 by Andrew Tridgell, Wayne Davison, and others.
Web site: http://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 32-bit timestamps, 64-bit long ints,
    socketpairs, hardlinks, symlinks, IPv6, batchfiles, inplace,
    append, ACLs, no xattrs, iconv, symtimes, prealloc
```

```Batchfile
$ vagrant up
Bringing machine 'rancher-01' up with 'virtualbox' provider...
==> rancher-01: Checking if box 'rancherio/rancheros' is up to date...
==> rancher-01: Clearing any previously set forwarded ports...
==> rancher-01: Clearing any previously set network interfaces...
==> rancher-01: Preparing network interfaces based on configuration...
    rancher-01: Adapter 1: nat
    rancher-01: Adapter 2: hostonly
==> rancher-01: Forwarding ports...
    rancher-01: 22 => 2222 (adapter 1)
==> rancher-01: Running 'pre-boot' VM customizations...
==> rancher-01: Booting VM...
==> rancher-01: Waiting for machine to boot. This may take a few minutes...
    rancher-01: SSH address: 127.0.0.1:2222
    rancher-01: SSH username: rancher
    rancher-01: SSH auth method: private key
    rancher-01: Warning: Connection timeout. Retrying...
    rancher-01: Warning: Remote connection disconnect. Retrying...
==> rancher-01: Machine booted and ready!
==> rancher-01: Configuring and enabling network interfaces...
==> rancher-01: Rsyncing folder: /d/VM/rancheros/ => /opt/rancher
==> rancher-01:   - Exclude: [".vagrant/", ".git/"]
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /d/VM/rancheros/
Guest path: /opt/rancher
Command: rsync --verbose --archive --delete --copy-links --chmod=ugo=rwX --no-perms --no-owner --no-group --rsync-path sudo rsync -e ssh -p 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i 'd:/VM/rancheros/.vagrant/machines/rancher-01/virtualbox/private_key' --exclude .vagrant/ --exclude .git/ /d/VM/rancheros/ rancher@127.0.0.1:/opt/rancher
Error: Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [Receiver=3.1.1]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(235) [sender=3.1.1]
```

**Comment by DJviolin** [comment]
Can we use smb to sync folders between Windows and RancherOS under Vagrant?

**Comment by gregory** [comment]
awesome! Is there any integration for docker-machine instead of vagrant?

**Comment by deniseschannon** [comment]
@gregory Are you looking to launch RancherOS with docker-machine? If so, this is already supported and documented: http://docs.rancher.com/os/running-rancheros/workstation/docker-machine/

Or are you looking for something else?

**Comment by gregory** [comment]
yes, that's actually what i used, but unfortunately it doesn't mount the volumes on OSX. 
You can reproduce this easily: `docker run -it --rm -v $(pwd):/code busybox ls /code`
