### ISSUE TITLE
Add AMI in European and APAC zones

### ISSUE THREAD

**Issue by runseb** [rancherio/os#65]
Hi, it seems that there are only AMI in US zones.
Could you add some for the european and APAC zones ?
thanks

**Comment by ibuildthecloud** [comment]
We'll try to get more images out there.  We definitely want to support all of the regions.  Our procedure for the first was release was a bit manual so if was just too time consuming to upload all the images.  It is being automated now.

@cloudnautique is there anything that @runseb could look at to try to create his own image for a different region?  Granted it will be beta-ish quality.

**Comment by ibuildthecloud** [comment]
We now have AMIs in 

ap-northeast-1
ap-southeast-1
ap-southeast-2
eu-west-1
sa-east-1

Please refer to the README.md for the AMI IDs.  eu-central-1 will come shortly.  There was some issues in that region that made the automation difficult.
