### ISSUE TITLE
RancherOS stuck on startup when there's no network connection

### ISSUE THREAD

**Issue by sheng-liang** [rancherio/os#69]
It gets stuck at "Running [5/10] network"

**Comment by wlan0** [comment]
@ibuildthecloud  -- The subsequent containers (cloud-init, userdocker) may depend on networking. Is the present behavior, of waiting to obtain a dhcp lease and consequently freezing bootup the right behavior?

**Comment by ibuildthecloud** [comment]
We will now hang for 1 minute waiting for DHCP per NIC and then give up.
