### ISSUE TITLE
Cannot find RANCHER_STATE partition on Hyper-V

### ISSUE THREAD

**Issue by sheng-liang** [rancherio/os#80]
It started just fine. I can also get on to the network and see /dev/sda. I was able to format the /dev/sda partition and give it the RANCHER_STATE label.

The problem is it fails to detect RANCHER_STATE partition after reboot.

**Comment by ibuildthecloud** [comment]
This problem is going to be the same as VMware SCSI I'm guessing.  HyperV needs a kernel model loaded but we run udev to late.  RancherOS is supposed reorder this so that we launch udev before mounting state.  This sound be released this week.
