### ISSUE TITLE
qemu-system-x86_64 -enable-kvm -cdrom rancheros.iso gives a kernel panic

### ISSUE THREAD

**Issue by zoobab** [rancherio/os#89]
qemu-system-x86_64 -enable-kvm -cdrom rancheros.iso gives:

Kernel panic - not syncing: Unable to mount rootfs on unknown block(2,0)

This is with the latest ISOs, including the released and unreleased ones.

**Comment by ibuildthecloud** [comment]
Please add `-m 1024`.  Needs more memory.

**Comment by deniseschannon** [comment]
@zoobab Please reopen if the memory fix didn't work.
