### ISSUE TITLE
rancherctl os upgrade should check first if upgraded is necessary

### ISSUE THREAD

**Issue by sheng-liang** [rancherio/os#92]
I'm already running 0.2.0-rc3, yet it still upgraded me to 0.2.0-rc3.

The system rebooted automatically after the upgrade. It should prompt me for reboot, at least put in a count down delay.

**Comment by deniseschannon** [comment]
In version v0.2.1, it prompts if you want to continue with the upgrade and prompts for a reboot. 

But the system still downloads the most recent version even if it's the same version as I'm running. It'd be nice if it would check to see if upgrade was needed before downloading the image.
