### ISSUE TITLE
option to enable "user_docker.args" during rancheros-install

### ISSUE THREAD

**Issue by henrysher** [rancherio/os#97]
I have a private docker registry and need to pass "--insecure-registry xx.xx.xx.xx:5000" during rancheros-install.

**Comment by ibuildthecloud** [comment]
Through the cloud config you can modify the arguments of user and system docker.  Refer to https://github.com/rancherio/os/blob/master/docs/config.md

**Comment by ibuildthecloud** [comment]
Oh I just noticed that you referenced user_docker.args in the title of this issue.  Did you try setting it in the cloud config and it didn't work?

**Comment by henrysher** [comment]
@ibuildthecloud it did not work. Finally i got a solution, to configure this parameter into **/var/lib/rancher/conf/rancher.yml** after **rancheros-install and reboot**. Thus, if the parameter "user_docker.args" can be supported in **rancheros-install** configuration, it will help me more easily and install once.
```
cloud_init:
  datasources:
  - file:/var/lib/rancher/conf/user_config.yml

user_docker:
  tls: false
  tls_args: [--tlsverify, --tlscacert=ca.pem, --tlscert=server-cert.pem, --tlskey=server-key.pem,
    '-H=0.0.0.0:2376']
  args: [docker, -d, -s, overlay, -G, docker, -H, 'unix:///var/run/docker.sock', '--insecure-registry x.x.x.x:5000']
```

**Comment by ibuildthecloud** [comment]
@henrysher It just dawned on me this isn't clearly documented.  I will update the documentation.  If you wish to configure the rancher.yml from the cloud config you must put the contents under the rancher key, for example:

```yaml
rancher:
  user_docker:
    args: [x,y,z]
```

**Comment by henrysher** [comment]
@ibuildthecloud i have tried, it works. thanks!

**Comment by ibuildthecloud** [comment]
I've documented the rancher key in the cloud-init at https://github.com/rancherio/os#cloud-init.  I'm closing this issue now.

**Comment by deniseschannon** [comment]
@chinaares Please look into using @joshwget's cloud config validator as your cloud config has errors. 

https://forums.rancher.com/t/online-cloud-config-validator/3530

Note: I added 3 backticks in front and after your code to make it a code block.
